apiVersion: v1
kind: Pod
metadata:
  name: sm-api
  namespace: staff-manager
  labels:
    app: sm-api
spec:
  containers:
    - name: sm-api
      image: mchekini/sm-api:1.0
      ports:
        - containerPort: 8080
      imagePullPolicy: Always
      startupProbe:
        httpGet:
          port: 8080
          path: /api/v1/health
        failureThreshold: 12
        periodSeconds: 10
      livenessProbe:
        httpGet:
          port: 8080
          path: /api/v1/health
        failureThreshold: 2
        successThreshold: 1
        periodSeconds: 10
      readinessProbe:
        httpGet:
          port: 8080
          path: /api/v1/health
        failureThreshold: 2
        successThreshold: 1
        periodSeconds: 10
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-access-key
              key: aws-access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret-key
              key: aws-secret-key
        - name: AWS_DEFAULT_REGION
          value: "us-east-2"

