version: '2'
services:
  staff-manager-api:
    container_name: staff-manager-api
    image: mchekini/staff-manager-api:${TAG}
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${ACTIVE_PROFILE}
  staff-manager-db:
    image: postgres
    container_name: staff-manager-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

networks:
  default:
    external:
      name: staff-manager


