version: '2'
services:
  staff-manager-api:
    container_name: staff-manager-api
    image: mchekini/staff-manager-api:${TAG}
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${ACTIVE_PROFILE}

networks:
  default:
    external:
      name: staff-manager


