spring:
  datasource:
    url: jdbc:postgresql://staff-manager-db:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver




bucket:
  justificatifs: int-justificatifs-check-consulting
  fiche-de-paie: int-fiche-de-paie-check-consulting
  factures: int-factures-check-consulting

