spring:
  datasource:
    url: jdbc-secretsmanager:postgresql://int-sm-db.chqar689pasc.us-east-2.rds.amazonaws.com:5432/postgres
    username: sm-int-db-credentials
    driverClassName: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver




bucket:
  justificatifs: int-justificatifs-check-consulting
  fiche-de-paie: int-fiche-de-paie-check-consulting
  factures: int-factures-check-consulting

