apiVersion: apps/v1
kind: Deployment
metadata:
    name: sm-api
    labels:
        application: sm-api
spec:
    replicas: 2
    selector:
        matchLabels: 
            application: sm-api
    template: 
        metadata:
            name: sm-api
            labels:
                application: sm-api
        spec:
            affinity:
                podAntiAffinity:
                  preferredDuringSchedulingIgnoredDuringExecution:
                    - weight: 100
                      podAffinityTerm:
                        topologyKey: topology.kubernetes.io/zone
            containers:
                - name: sm-api
                  image: mchekini/staff-manager-api:1.0.0
                  startupProbe:
                    httpGet:
                      port: 8080
                      path: /api/v1/healthcheck
                    failureThreshold: 12
                    periodSeconds: 10
                  livenessProbe:
                    httpGet:
                      port: 8080
                      path: /api/v1/healthcheck
                    failureThreshold: 2
                    successThreshold: 1
                    periodSeconds: 10
                  readinessProbe:
                    httpGet:
                      port: 8080
                      path: /api/v1/healthcheck
                    failureThreshold: 2
                    successThreshold: 1
                    periodSeconds: 10
                  imagePullPolicy: Always
                  ports: 
                    - containerPort: 8080 
                  env:
                    - name: SPRING_PROFILES_ACTIVE
                      value: prod
                    - name: POD_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.name
                    - name: AWS_ACCESS_KEY_ID
                      valueFrom:
                        secretKeyRef:
                          name: aws-access-key
                          key: aws-access-key
                    - name: AWS_SECRET_ACCESS_KEY
                      valueFrom:
                        secretKeyRef:
                          name: aws-secret-key
                          key: aws-secret-key
                    
